[tool.aerich]
tortoise_orm = "app.db.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.pytest.ini_options]
addopts = "-W ignore::DeprecationWarning" #-p no:warnings 

[tool.coverage.run]
branch = true
omit = ["tests/*"]

[tool.ruff]
line-length = 100
exclude = [
  ".git",
  ".mypy_cache",
  ".pre-commit-cache",
  ".ruff_cache",
  ".tox",
  ".venv",
  "venv",
  "docs",
  "__pycache",
  "**/migrations/*",
]